name: multipurpose_widgetkit
description: Multipurpose widget for any apps.
version: 0.0.1
repository: https://github.com/ajianaz/multipurpose_widgetkit

environment:
  sdk: ^3.0.6
  flutter: '>=3.0.0'

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_jailbreak_detection: ^1.10.0
  google_sign_in: ^6.1.4
  google_sign_in_platform_interface: ^2.4.1
  google_sign_in_web: ^0.12.0+3
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  package_info_plus: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

flutter:
