name: multipurpose_widgetkit
description: Multipurpose widget for any apps.
version: 0.0.1
repository: https://github.com/ajianaz/multipurpose_widgetkit

environment:
  sdk: ^3.0.6
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

flutter:
